resources:
  - name: dwpdigital-dataworks-rbac-munge-policies
    type: registry-image-resource
    source:
      repository: dwpdigital/dataworks-rbac-munge-policies
    check_every: 5m

  - name: ecr-dwpdigital-dataworks-rbac-munge-policies-dev
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "dataworks-rbac-munge-policies"

  - name: ecr-dwpdigital-dataworks-rbac-munge-policies
    .: (( inject meta.resources.ecr-resource ))
    source:
      repository: "dataworks-rbac-munge-policies"
      aws_role_arn: arn:aws:iam::((dataworks.aws_management_acc)):role/ci

jobs:
  - name: mirror-dwpdigital-dataworks-rbac-munge-policies-dev
    serial_groups: [dataworks-rbac-munge-policies]
    plan:
      - get: dwpdigital-dataworks-rbac-munge-policies
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-dataworks-rbac-munge-policies-dev
        params:
          image: "dwpdigital-dataworks-rbac-munge-policies/image.tar"
        attempts: 3

  - name: mirror-dwpdigital-dataworks-rbac-munge-policies
    serial_groups: [dataworks-rbac-munge-policies]
    plan:
      - get: dwpdigital-dataworks-rbac-munge-policies
        trigger: true
        params:
          format: oci
        attempts: 3
      - put: ecr-dwpdigital-dataworks-rbac-munge-policies
        params:
          image: "dwpdigital-dataworks-rbac-munge-policies/image.tar"
        attempts: 3
